# Generated by Django 4.1.7 on 2023-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
