# Generated by Django 4.1.7 on 2023-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0002_user_delete_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("USER", "USER")],
                default="USER",
                max_length=50,
            ),
        ),
    ]
