# Generated by Django 4.1.7 on 2023-04-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0003_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
