# Generated by Django 4.1.7 on 2023-05-27 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "types",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField()),
                ("amount", models.FloatField(default=0)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[("INCREASE", "INCREASE"), ("DECREASE", "DECREASE")],
                        default="INCREASE",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="", max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("fund_goal", models.FloatField(default=0)),
                ("fund_total", models.FloatField(default=0)),
                ("fund_used", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("DEACTIVATED", "DEACTIVATED"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "type_projects",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="api_project.type"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ("-created_at",),
            },
        ),
    ]
