# Generated by Django 4.1.7 on 2023-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
