# Generated by Django 4.1.7 on 2023-05-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="name",
        ),
        migrations.AddField(
            model_name="transaction",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api_project.project",
            ),
            preserve_default=False,
        ),
    ]
