# Generated by Django 4.1.7 on 2023-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_project", "0005_project_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
