# Generated by Django 4.1.7 on 2023-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_project", "0006_alter_transaction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="full_name",
            field=models.CharField(blank=True, default="Anonymous", max_length=255),
        ),
    ]
