# Generated by Django 4.1.7 on 2023-06-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_project", "0007_alter_transaction_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="description",
            new_name="message",
        ),
    ]
