# Generated by Django 4.1.7 on 2023-06-20 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api_project", "0008_rename_description_transaction_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("FINISHED", "FINISHED"),
                    ("INACTIVE", "INACTIVE"),
                ],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.FloatField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="api_project.project",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ("-created_at",),
            },
        ),
    ]
